# Generated by Django 2.2.1 on 2019-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50)),
                ('ingredient_ID', models.CharField(max_length=50)),
                ('ingredient_price', models.CharField(max_length=50)),
            ],
        ),
    ]
