# Generated by Django 2.2.1 on 2019-05-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlbionCraft', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
