# Generated by Django 2.2.1 on 2019-05-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbionCraft', '0002_auto_20190516_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_ID', models.CharField(max_length=50)),
                ('food_price', models.CharField(max_length=50)),
            ],
        ),
    ]
